from dgad.prediction import Detective


# -----------------------------------------------------------
# Hunt domains generated by Domain Generation Algorithms
# -----------------------------------------------------------
def is_dga_domain(domain):
    temp_domains = [domain]
    detective = Detective()
    # convert temp_domains strings into dgad.schema.Domain
    temp_domains, _ = detective.prepare_domains(temp_domains)
    # classify them
    detective.investigate(temp_domains)
    # return if the domain is dga generated
    return temp_domains[0].is_dga
