version: '2'
services:
  cartuxeira:
    build: .
    image: 3grander/cartuxeira:0.1.0
    container_name: cartuxeira
    networks:
      - mdb
    entrypoint: python cartuxeira.py -s 0.0.0.0 -p 5000 -m cartuxeiradb -mp 27017
    ports:
      - "5000:5000"
    depends_on:
      - cartuxeiradb
  cartuxeiradb:
    image: mongo
    container_name: cartuxeiradb
    networks:
      - mdb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
networks:
  mdb:
    external: false