#
# Copyright 2023 The Cartuxeira Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import joblib
from tensorflow import keras
from analysis.dgaDetect.dga_detect import is_dga_domain
import warnings
warnings.simplefilter('ignore', UserWarning)

# Constants
validChars = {'t': 1, 'k': 2, '7': 3, 'h': 4, 's': 5, 'e': 6, 'f': 7, 'b': 8, 'n': 9, 'o': 10, 'a': 11, '+': 12,
              'j': 13, '8': 14, 'y': 15, '0': 16, 'c': 17, '2': 18, '1': 19, 'l': 20, '4': 21, '.': 22, 'g': 23,
              'd': 24, 'i': 25, '-': 26, 'r': 27, '6': 28, 'v': 29, '3': 30, '_': 31, 'z': 32, 'q': 33, '5': 34,
              'u': 35, 'p': 36, '9': 37, 'x': 38, 'w': 39, 'm': 40}

estimator = joblib.load('models/ega.joblib')


# -----------------------------------------------------------
# Hunt emails generated by Email Generation Algorithms
# -----------------------------------------------------------
def is_ega_email(email):
    # Init
    domain = email.split('@')[1]
    local_part = email.split('@')[0]

    # Checks if local_part is DGA
    if is_dga_domain(local_part):
        return True

    # Checks if local_part or domain is EGA
    if __is_ega(local_part) or __is_ega(domain):
        return True

    # Return default
    return False


# -- Private functions
def __is_ega(name):
    x = [[validChars[y] for y in name]]
    x2 = keras.preprocessing.sequence.pad_sequences(x, maxlen=118)
    return bool(int(estimator.predict(x2)))
